### ISSUE TITLE
Where the color information is stored?

### ISSUE THREAD

**Issue by BurguerJohn** [vt-vl-lab/3d-photo-inpainting#10]
I managed to open the .ply file in other applications, but all the triangles are greyed out. I'm not sure if this is a bug since the model have 5M polygons.
Is each triangle colored with the color of the original image or it use the original image as a texture? I was not able to use the image as a texture.
Follow up question, it is possible to generate a model with fewer triangles by changing some variable?

**Comment by safijari** [comment]
Based on what little I've been able to understand of the code, yes, it uses vertex coloring. The mesh resolution seems to be the same as the depth map resolution so you could change that and make it more coarse but then you'll get worse edges and much lower res image overall.

**Comment by LemonATsu** [comment]
@safijari @BurguerJohn Yep, color information is stored in vertices.

**Comment by ShihMengLi** [comment]
Yes, we simply use vertex_color to store the results which makes the memory size of 3-D mesh really huge.
We will apply mesh simplification and store the color information into uv-texture maps when we are available in the future. This will greatly reduce the size of 3-D mesh.

**Comment by BurguerJohn** [comment]
Alright, thanks everyone for the explanation.
