### ISSUE TITLE
AttributeError: 'LooseVersion' object has no attribute 'version

### ISSUE THREAD

**Issue by Nerdyvedi** [vt-vl-lab/3d-photo-inpainting#101]
Hi,
I am trying to run it in a ssh session, with Ubuntu OS.
I have set offline_rendering option to True. 

Getting this error even when running with CPU

**Comment by LemonATsu** [comment]
It seems to be a Qt/Vispy package related problem. I will recommend you to check their repo if someone has reported similar issues.

**Comment by Nerdyvedi** [comment]
It's an error related to OpenGL is all I am able to figure out. Why do you think I am getting it even when I am running the program on CPU?

**Comment by LemonATsu** [comment]
The mesh rendering part is done using openGL, regardless of which device you are running the model with.

**Comment by Nerdyvedi** [comment]
It runs fine on CPU, but facing this issue on the ssh session. Maybe, It has to do something with running OpenGL on remote server.

**Comment by LemonATsu** [comment]
You need to have EGL installed to get offscreen rendering works in a remote ssh session
