### ISSUE TITLE
Edge Connect License 

### ISSUE THREAD

**Issue by MattToul** [vt-vl-lab/3d-photo-inpainting#104]
Hello, 

Thank you sharing this amazing project, would it be possible to know which parts of the code fall under the Edge Connect Creative Commons Non-Commercial License ? 

Thank you, 

Best,

**Comment by CharStiles** [comment]
Hi, +1 on this question

**Comment by LemonATsu** [comment]
Not quite sure about that. You can reach out to the authors of Edge Connect.

**Comment by cuixinye** [comment]
@ShihMengLi I find similarity between [networks.py](https://github.com/vt-vl-lab/3d-photo-inpainting/blob/master/networks.py) and [edge-connect/src/networks.py](https://github.com/knazeri/edge-connect/blob/master/src/networks.py). Is this the reason you add the LICENSE FOR EdgeConnect? But even EdgeConnect's file, it's not fully original. Could you please check the code and update the license?
