### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by filipppp** [vt-vl-lab/3d-photo-inpainting#11]
Do you know how to change the backend properly for vispy (since I use windows)? I tried using pyqt5 instead of EPL but the new git version doesnt work with that. (probably the circle animation..) It gives following error with pyqt5:
```
(3DP) E:\3d>python main.py --config argument.yml
  0%|                                                                                            | 0/2 [00:00<?, ?it/s]Current Source ==>  beatles
initialize
device: cpu
start processing
  processing image\beatles.jpg (1/1)
torch.Size([1, 3, 384, 384])
finished
53.13010235415598
WARNING: Although PyQt5 is already imported, the PyQt5 backend could not
be used ("DLL load failed: The specified procedure could not be found.").
Note that running multiple GUI toolkits simultaneously can cause side effects.
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    videos_poses, video_basename, config.get('original_h'), config.get('original_w'), border=border, depth=depth, normal_canvas=normal_canvas, all_canvas=all_canvas)
  File "E:\3d\mesh.py", line 2203, in output_3d_photo
    proj='perspective')
  File "E:\3d\mesh.py", line 2132, in __init__
    self.canvas = scene.SceneCanvas(bgcolor=bgcolor, size=(canvas_size*factor, canvas_size*factor))
  File "C:\Users\Filip\anaconda3\envs\3DP\lib\site-packages\vispy\scene\canvas.py", line 137, in __init__
    always_on_top, px_scale)
  File "C:\Users\Filip\anaconda3\envs\3DP\lib\site-packages\vispy\app\canvas.py", line 169, in __init__
    self._app = use_app(call_reuse=False)
  File "C:\Users\Filip\anaconda3\envs\3DP\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "C:\Users\Filip\anaconda3\envs\3DP\lib\site-packages\vispy\app\application.py", line 49, in __init__
    self._use(backend_name)
  File "C:\Users\Filip\anaconda3\envs\3DP\lib\site-packages\vispy\app\application.py", line 256, in _use
    'PyQt' % [b[0] for b in CORE_BACKENDS])
RuntimeError: Could not import any of the backends. You need to install any of ['PyQt4', 'PyQt5', 'PySide', 'PySide2', 'Pyglet', 'Glfw', 'SDL2', 'wx', 'EGL', 'osmesa']. We recommend PyQt
  0%|
```

pyqt5 is installed, this issue started since arrays were added into the argument.yml file

**Comment by LemonATsu** [comment]
Strange. Would you mind telling us which commit works for you previously?

**Comment by filipppp** [comment]
#58b32fb304e3f4aa5c3299819378c82a959536ef seemed to change the argument.yml, so I assume I cloned it before that.

**Comment by LemonATsu** [comment]
I see. So in that particular version, `vispy.use("pyqt5")` (or `vispy.use("egl")`) works for you?

**Comment by filipppp** [comment]
I had to add `vispy.use("PyQt5")`

**Comment by LemonATsu** [comment]
> I had to add `vispy.use("PyQt5")`

Alright, we will look into that.

**Comment by filipppp** [comment]
Can confirm again, tested it out on https://github.com/vt-vl-lab/3d-photo-inpainting/commit/b4670e63e27574bafab6fc28278e0db2efe36599 , works fine with pyqt5

**Comment by LemonATsu** [comment]
@filipppp Can you try calling `vispy.use("PyQt5")` right after `import vispy`?

**Comment by filipppp** [comment]
> @filipppp Can you try calling `vispy.use("PyQt5")` right after `import vispy`?

No still doesnt work.
`import numpy as np
import argparse
import glob
import os
from functools import partial
import vispy
import yaml
parser = argparse.ArgumentParser()
parser.add_argument('--config', type=str, default='argument.yml',help='Configure of post processing')
args = parser.parse_args()
config = yaml.load(open(args.config, 'r'))
if config['offscreen_rendering'] is True:
    vispy.use(app='egl')`

**Comment by LemonATsu** [comment]
Sorry for the confusion, I mean something like:
```
import vispy
vispy.use(app="PyQt5")
import yaml
...
```
Set the backend immediately after the import statement. Throw away the if-else statement here.

**Comment by ShihMengLi** [comment]
You can edit the flag `offscreen_rendering` in the `argument.yml`. 
(i.e. `offscreen_rendering: True` --> `offscreen_rendering: False`)

**Comment by filipppp** [comment]
Works now! @LemonATsu Maybe you should add in the documentation that the `vispy.use()` line has to be changed and pyqt5 has to be installed

**Comment by LemonATsu** [comment]
Cool, glad it works. We will revise the readme correspondingly.

**Comment by eps696** [comment]
just to let you know that all worked for me out-of-the-box with pyglet backend (had only that one installed). system versions: windows 10, cuda 10.0, cudnn 7.5.0, pytorch 1.2.0, pyglet 1.5.x

**Comment by boraturant** [comment]
> just to let you know that all worked for me out-of-the-box with pyglet backend (had only that one installed). system versions: windows 10, cuda 10.0, cudnn 7.5.0, pytorch 1.2.0, pyglet 1.5.x

are you on GPU?
are you on requested config in readme?(Anaconda...)
are you on local or remote machine(EC2)?

Thanks, couldn't  seem to make it work on Windows.

**Comment by boraturant** [comment]
ok, it looks like it works out-of-the-box on GPU enabled win (EC2)

**Comment by eps696** [comment]
@boraturant i'm on local machine (not EC2), with GPU

**Comment by BongMinJo** [comment]
import vispy
vispy.use(app="PyQt5")
import yaml

modified and executed as
However, this error occurs.

running on device cpu
  0%|                            | 0/1 [00:00<?, ?it/s]Current Source ==>  moon
Running depth extraction at 1588351085.1326828
initialize
device: cpu
start processing
  processing image/moon.jpg (1/1)
torch.Size([1, 3, 384, 384])
finished
Start Running 3D_Photo ...
Loading edge model at 1588351098.2483711
Loading depth model at 1588351098.5806098
Loading rgb model at 1588351100.0460534
Writing depth ply (and basically doing everything) at 1588351101.7283363
Writing mesh file mesh/moon.ply ...
Making video at 1588351346.1545823
fov: 53.13010235415598
WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-heeji'
WARNING: QXcbConnection: Could not connect to display 
WARNING: Could not connect to any X display.

I am currently operating with cpu in wsl environment and am installing qypt5. How do I resolve this error?

**Comment by LemonATsu** [comment]
@BongMinJo Try setting the `offscreen_rendering` in `argument.yml` to `True.`

**Comment by BongMinJo** [comment]
@LemonATsu I try setting the offscreen_rendering in argument.yml to True. 
But same errors occur
running on device cpu
  0%|                                                                                                                                | 0/1 [00:00<?, ?it/s]Current Source ==>  moon
Running depth extraction at 1588392916.9544208
initialize
device: cpu
start processing
  processing image/moon.jpg (1/1)
torch.Size([1, 3, 384, 384])
finished
Start Running 3D_Photo ...
Loading edge model at 1588392933.4545689
Loading depth model at 1588392933.6984227
Loading rgb model at 1588392934.855371
Writing depth ply (and basically doing everything) at 1588392936.0844417
Writing mesh file mesh/moon.ply ...
Making video at 1588393252.0888572
fov: 53.13010235415598
WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-heeji'
WARNING: QXcbConnection: Could not connect to display 
WARNING: Could not connect to any X display.
