### ISSUE TITLE
It takes 2-3 minutes on COLAB

### ISSUE THREAD

**Issue by hana9090** [vt-vl-lab/3d-photo-inpainting#12]
That's really a piece of art. I love it :)

I tested it using COLAB GPU and it takes 2-3 minutes, so if it works on gpu why it takes this time? Or do I miss something here?
Thanks

**Comment by ShihMengLi** [comment]
I think the code has not been optimized. 
For example, the read/write of 3-D mesh takes lots of time. We are now managing to accelerate the process.

**Comment by abhinavsp0730** [comment]
would you please provide your colab notebook I'm having errors while running into colab?
@hana9090

**Comment by hana9090** [comment]
@ShihMengLi  Thanks.
@abhinavsp0730 I used the same notebook on this repository.

**Comment by nems808** [comment]
Actually when I run this example on my machine it says it uses the CPU but when I change the gpu_ids to 1 in argument.yml I get this error: 

RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device

What is the correct way to set it up so it uses my GPU instead?

**Comment by LemonATsu** [comment]
The log about using cpu is only for the depth model. See #8 
The error occurs because you only have one gpu (gpu_ids={0}), but you set it to 1 (which is invalid).

**Comment by kwea123** [comment]
Concerning ply file i/o, I recommend a package: `plyfile` that can easily write (N, ?) numpy arrays into ply format, so you don't need for loops anymore.
