### ISSUE TITLE
RTX 3XXX Series Not Supported

### ISSUE THREAD

**Issue by 78Alpha** [vt-vl-lab/3d-photo-inpainting#130]
Thought to give my new GPU test on BMD mixed with 3DP but noticed some suspicious slowness, a process that should have taken 10 minutes was taking 7 hours. I worked down the list of why and thought to test BMD on its own, and sure enough, it provided the information I needed. It gives a warning that the RTX 3070 in my system has a newer compute version than is supported, and instead of defaulting to my RTX 2060 (this is supported and works in seconds), it defaults to a single CPU thread (1/16).

The same issue is found in 3DP, but 3DP does not report the issue like BMD does, it instead just tries to move forward.

`conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge `

on the pytorch page makes the card work and the results are not altered by the change

**Comment by powernic** [comment]
@78Alpha I have built a docker container for my RTX3070 card and it works great on WSL, you can try using
https://github.com/powernic/docker_3d-photo-inpainting

**Comment by yunhhp12** [comment]
@78Alpha This helped me a lot thanks!

**Comment by vgaggia** [comment]
Hey, i'm trying to get this to work, i'm using a 30xx series card as well, but in docker i'm getting 
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
I do obviously have my drivers installed i've used wsl to do some stuff in the past with other repos, but i just can't get thiis repo to work

**Comment by powernic** [comment]
@vgaggia What OS build version do you have?
https://docs.nvidia.com/cuda/wsl-user-guide/index.html

2.1. WSL 2 System Requirements
Ensure you are registered on Windows Insider Program and subscribing to the Dev Channel and OS build is 20145 or later. We recommend at least OS 21390 or higher for latest features and performance updates.
Windows 11 is supported. Refer to Windows 11 system requirements.
Ensure the WSL Kernel installed is the latest version or at least 4.19.121+. Once again, we recommend 5.10.16.3 or later for better performance.
WSL2 GPU acceleration will be available on Pascal and later GPU architecture on both GeForce and Quadro product SKUs in WDDM mode. It will not be available on Quadro GPUs in TCC mode or Tesla GPUs yet.

**Comment by vgaggia** [comment]
I'm running windows 11 build 22000

**Comment by powernic** [comment]
@vgaggia What version of linux are you using in wsl? Does the card work in wsl? has the driver been installed in linux according to the instructions? https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by vgaggia** [comment]
So i decided to just ditch wsl and setup a bare metal ubuntu system, i setup the default 3dp with the updated cudatoolkit for 30 series and i'm now getting  Segmentation fault (core dumped), btw i'm using a rtx 3060 non ti.

![Screenshot from 2021-08-17 23-33-51](https://user-images.githubusercontent.com/1644490/129803665-811814ae-56af-4820-937b-4cce2b047b03.png)

(edit)
Is there no way to emulate older versions of cuda i wonder?

**Comment by austinask** [comment]
> 

Did you ever solve this? I have the same error

**Comment by vgaggia** [comment]
No i think i ended up just using google collab unfortunately.

**Comment by austinask** [comment]
Thanks for the response, I had ended up doing the same.
