### ISSUE TITLE
error main.py

### ISSUE THREAD

**Issue by VrushankMPC** [vt-vl-lab/3d-photo-inpainting#148]
I am getting this error, can anyone help?

(3DP) D:\3D\3d-photo-inpainting-master>python main.py --config argument.yml
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    config = yaml.load(open(args.config, 'r'))
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by KyleQiLiu** [comment]
In main.py change at line 29
change the yaml.load to yaml.safe_load
