### ISSUE TITLE
[Colab] Will only inpaint the default image, and upon deleting that image, will not generate results at all.

### ISSUE THREAD

**Issue by CrimsonCuttle** [vt-vl-lab/3d-photo-inpainting#162]
In Google Colab, I will run every cell until the "Please upload .jpg files to [/content/3d-photo-inpainting-master/image](https://colab.research.google.com/drive/1706ToQrkIZshRSJSHvZ1RuCiM__YX3Bz#)/" one, delete the provided "moon.jpg" and then I will run the cell to upload my own picture (also named "moon.jpg" because I haven't found a way to direct the program to any other file), run the final cell to execute the inpainting, and then the result will still be of the default moon.jpg picture, instead of my own. Deleting these video files and then trying to run the inpainting again will result in no video files or mesh being generated at all. I don't understand what's going on here.

EDIT: Small update, changing the img type to png makes it work somewhat, but only generates one video, and I'm unsure how to change which type of video is generated.

**Comment by Michaelwhite34** [comment]
You just run the cell to upload jpg file, it will use that uploaded file.

**Comment by CrimsonCuttle** [comment]
> You just run the cell to upload jpg file, it will use that uploaded file.

Except it does not. It does nothing.

**Comment by CrimsonCuttle** [comment]
I believe I found the solution to my issue. While simply renaming a file from .png to .jpg worked for me twice before, it seems it no longer does. I wonder why.
