### ISSUE TITLE
cudatoolkit==10.1 ?

### ISSUE THREAD

**Issue by deeplook** [vt-vl-lab/3d-photo-inpainting#2]
Are you sure it's `cudatoolkit==10.1`? To me that seems hard to find on anaconda.org...

**Comment by ShihMengLi** [comment]
Try `cudatoolkit==10.1.243` instead. Let us know if it works. Thanks.
`conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit==10.1.243 -c pytorch`
