### ISSUE TITLE
Job is aborted due to Qt plugin issue.

### ISSUE THREAD

**Issue by RobinSeaside** [vt-vl-lab/3d-photo-inpainting#24]
"WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)"

My OS: Linux kelut 4.18.0-147.5.1.el8_1.x86_64 #1 SMP

**Comment by LemonATsu** [comment]
Have you tried setting `offscreen_render=True` in your `argument.yml`?

**Comment by RobinSeaside** [comment]
> Have you tried setting `offscreen_render=True` in your `argument.yml`?

Thank you for your prompt reply. :)  I did not try 'offscreen_render=True'. Let me try later and come back to you.

I ran your app successfully using my macbook. great job Shih-Yang

**Comment by RobinSeaside** [comment]
> > Have you tried setting `offscreen_render=True` in your `argument.yml`?
> 
> Thank you for your prompt reply. :) I did not try `offscreen_render=True` Let me try later and come back to you.
> 
> I ran your app successfully using my macbook. great job Shih-Yang

I'd like to confirm that setting `offscreen_render=True` can fix this issue. Closing the issue now.
