### ISSUE TITLE
Load exported mesh files

### ISSUE THREAD

**Issue by loretoparisi** [vt-vl-lab/3d-photo-inpainting#27]
Hi have exported the  `.ply` mesh file to meshlab, but I'm not sure if I get the right visualization here.

<img width="1680" alt="Schermata 2020-04-17 alle 20 17 59" src="https://user-images.githubusercontent.com/163333/79601108-8fb51a00-80e8-11ea-85be-813b0fe5b385.png">

**Comment by ShihMengLi** [comment]
Could you paste the camera pose here?
You could follow the instruction here.
[https://sourceforge.net/p/meshlab/discussion/499533/thread/cc40efe0/#86ad](url)

**Comment by loretoparisi** [comment]
@ShihMengLi thanks this is the output of Cmd-C / Cmd-V (macOS)

```
<!DOCTYPE ViewState>
<project>
 <VCGCamera TranslationVector="3.05245 5.91232 -38.3265 1" PixelSizeMm="0.0369161 0.0369161" FocalMm="29.2208" RotationMatrix="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 " BinaryData="0" LensDistortion="0 0" CenterPx="604 457" CameraType="0" ViewportPx="1209 914"/>
 <ViewSettings TrackScale="0.111363" FarPlane="7.83083" NearPlane="0.303109"/>
</project>
```

**Comment by ShihMengLi** [comment]
@loretoparisi , Thanks. Could you paste the following content into the `meshlab` window.

<!DOCTYPE ViewState>
<project>
 <VCGCamera TranslationVector="0 0 0 0" PixelSizeMm="0.0369161 0.0369161" FocalMm="29.2208" RotationMatrix="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 " BinaryData="0" LensDistortion="0 0" CenterPx="604 457" CameraType="0" ViewportPx="1209 914"/>
 <ViewSettings TrackScale="0.111363" FarPlane="7.83083" NearPlane="0.303109"/>
</project>

**Comment by loretoparisi** [comment]
@ShihMengLi thank you. So if I change with this camera view, now it's a bitter better
<img width="735" alt="Schermata 2020-04-22 alle 22 08 57" src="https://user-images.githubusercontent.com/163333/80028785-f28e2300-84e5-11ea-9eea-2da9e371f7ee.png">

I can see the image like extruded and upside-down

**Comment by kwea123** [comment]
You need to change camera view and zoom in. The depth has a wide range, that's why there's a huge long tail in the mesh. I tried with the default moon.jpg and the mesh looks good.
