### ISSUE TITLE
Colab seems to unnecessarily reinstall torch?

### ISSUE THREAD

**Issue by jelos98** [vt-vl-lab/3d-photo-inpainting#28]
I _believe_ that this line in your colab is unnecessary:

!pip3 install torch==1.4.0+cu100 torchvision==0.5.0+cu100 -f 
 https://download.pytorch.org/whl/torch_stable.html

Colab by default seems to have cuda enabled 1.4.0 and 0.5.0 - is there a reason to force the specific version here? It seems to work fine-ish without doing so, and having the reinstall introduces a fairly hefty initial delay.

**Comment by LemonATsu** [comment]
Yep, it can work fine without the two lines for now. However, we want to ensure that the code is operable even if colab changes the default version in the future. Hope this makes sense to you.
