### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'node'

### ISSUE THREAD

**Issue by ShuperDark** [vt-vl-lab/3d-photo-inpainting#31]
I set the value of gpu_ids in the argument.yml to -1 because it was giving me the error "RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU." until earlier.
However, this time I got an error that said "AttributeError: 'Graph' object has no attribute 'node'". 

What am I supposed to do?

**Comment by MarioProjects** [comment]
I have the same error: Graph' object has no attribute 'node'

> Traceback (most recent call last):
>   File "main.py", line 95, in <module>
>     depth_feat_model)
>   File "/home/maparla/2dto3d/3d-photo-inpainting/mesh.py", line 1841, in write_ply
>     input_mesh, info_on_pix, edge_mesh, depth, aft_mark = remove_dangling(input_mesh, edge_ccs, edge_mesh, info_on_pix, image, depth, config)
>   File "/home/maparla/2dto3d/3d-photo-inpainting/mesh.py", line 751, in remove_dangling
>     mesh = refresh_node(single_edge_node, mesh.node[single_edge_node], new_node, dict(), mesh)
> AttributeError: 'Graph' object has no attribute 'node'

**Comment by MarioProjects** [comment]
Okey @ShuperDark I saw it... https://github.com/vt-vl-lab/3d-photo-inpainting/issues/5

> Could you show the version of package networkx ?
> This should be networkx==2.3.
> The attribute 'node' has been deprecated since version 2.4.

**Comment by ShuperDark** [comment]
> Okey @ShuperDark I saw it... #5
> 
> > Could you show the version of package networkx ?
> > This should be networkx==2.3.
> > The attribute 'node' has been deprecated since version 2.4.

Oh, no! I didn't know we had the same issues😅
Is there a command to downgrade?

**Comment by MarioProjects** [comment]
```
pip uninstall networkx
pip install networkx==2.3
```

**Comment by ShuperDark** [comment]
> ```
> pip uninstall -y networkx
> pip install networkx==2.3
> ```

It's working! Thank you!

**Comment by MarioProjects** [comment]
:D Close the issue
