### ISSUE TITLE
Flight path definition

### ISSUE THREAD

**Issue by flipflopbboi** [vt-vl-lab/3d-photo-inpainting#33]
Could you please provide some more information on how we can customise the flight path (beyond editing the three params in `arguments.yml` which is quite limited compared what is actually doable here)? Is there a way to provide "coordinates" and which are the methods to be edited? Thank you very much for sharing tour brilliant work!

**Comment by eps696** [comment]
there's `path_planning` function in the `utils.py` file. have a look at 'circle' part as an example of adding custom points. output shapes must be (250,) for each of for xs, ys, zs.
