### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by cahitatlas** [vt-vl-lab/3d-photo-inpainting#37]
I use macOS Catalina, i can run project on pycharm but when i try to run on terminal i get that result:
I followed all steps again again. I didn't get any error, but can't start on terminal. 

![image](https://user-images.githubusercontent.com/25583152/80286544-b8ff2700-8734-11ea-8d09-7770086465da.png)

**Comment by LemonATsu** [comment]
Seems like you are not in the correct env/virtualenv when you are running the python scripts.

**Comment by cahitatlas** [comment]
Thanks @LemonATsu .
I changed Env with use "export PATH=~/anaconda3/bin:$PATH" on terminal.

**Comment by LemonATsu** [comment]
@cahitatlas You need to activate your virtualenv using `conda activate <your_env_name>`. Please refer to the Prerequisites for instruction about setting up your environment(s). Thanks
