### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'node'

### ISSUE THREAD

**Issue by cahitatlas** [vt-vl-lab/3d-photo-inpainting#39]
I encountered that error. How can i fix that.
![image](https://user-images.githubusercontent.com/25583152/80324783-0d8cca00-883b-11ea-8f26-87bbd266d353.png)

**Comment by berkutx** [comment]
pip uninstall -y networkx
pip install networkx==2.3

**Comment by LemonATsu** [comment]
Thanks, @berkutx. Also, check #31

**Comment by gateway** [comment]
I just ran into this as well... kinda odd that requirements has 2.3 listed, but on ubuntu 18 it throws the error above..
