### ISSUE TITLE
Only works if file name is moon.jpg

### ISSUE THREAD

**Issue by teylerk** [vt-vl-lab/3d-photo-inpainting#4]
This is an amazing piece of code!
Currently only works for me in collab and on my mac in conda if the filename is moon.jpg.

Thanks

**Comment by LemonATsu** [comment]
You can set the `specific` flag in argument.yml to '', or the image that you want to process.

**Comment by ShihMengLi** [comment]
Also, we have changed the default value of `specific` flag from "moon" to an empty string so that you could generate the video for every `.jpg` file now. 
Please pull the latest version,  thanks!
