### ISSUE TITLE
Newer version of midas model?

### ISSUE THREAD

**Issue by safijari** [vt-vl-lab/3d-photo-inpainting#41]
I noticed you are using the version of midas from July 2019. That repo was updated with a new model based on resnet101 in December and in the paper they mention that it was better than their resnet50 model. Did you have a chance to try the larger model?

**Comment by LemonATsu** [comment]
@safijari yes, we did try the new model a bit, and it also works, but the improvement is kinda minor (tested on our testing samples). Therefore, we stick with the Resnet50 for a cheaper computational cost.
