### ISSUE TITLE
Is there any way to work around if my CUDA out of memory?

### ISSUE THREAD

**Issue by HelixNGC7293** [vt-vl-lab/3d-photo-inpainting#43]
Hello! Thanks for sharing this project!
I just got an issue when trying to generate the target video:

> Start Running 3D_Photo ...
>   0%|                                                                                                                                    | 0/3 
> Traceback (most recent call last):
>   File "main.py", line 98, in <module>
>     depth_feat_model)
>   File "C:\Users\dagu_\Downloads\3d-photo-inpainting-master\mesh.py", line 1865, in write_ply
>     depth_edge_model, depth_feat_model, rgb_model, config, direc="up")
>   File "C:\Users\dagu_\Downloads\3d-photo-inpainting-master\mesh_tools.py", line 201, in extrapolate
>     cuda=device)
>   File "C:\Users\dagu_\Downloads\3d-photo-inpainting-master\networks.py", line 311, in forward_3P
>     edge_output = self.forward(enlarge_input)
>   File "C:\Users\dagu_\Downloads\3d-photo-inpainting-master\networks.py", line 325, in forward
>     x7 = self.decoder_2(torch.cat((x6, x1), dim=1))
>   File "G:\Tools\Anaconda3\envs\3dp\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "G:\Tools\Anaconda3\envs\3dp\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
>     input = module(input)
>   File "G:\Tools\Anaconda3\envs\3dp\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "G:\Tools\Anaconda3\envs\3dp\lib\site-packages\torch\nn\modules\padding.py", line 163, in forward
>     return F.pad(input, self.padding, 'reflect')
>   File "G:\Tools\Anaconda3\envs\3dp\lib\site-packages\torch\nn\functional.py", line 2879, in pad
>     return torch._C._nn.reflection_pad2d(input, pad)
> **RuntimeError: CUDA out of memory. Tried to allocate 100.00 MiB (GPU 0; 2.00 GiB total capacity; 1.17 GiB already allocated; 87.93 MiB free; 1.22 GiB reserved in total by PyTorch)**

It seems like my GPU capacity is not large enough.... Is there any way to solve this? I'm using GTX960M (I know it's kinda old DX)

Thank you so much!!~

**Comment by LemonATsu** [comment]
You can try it with our colab notebook if your GPU does not have enough memory.

**Comment by HelixNGC7293** [comment]
It works!! Thank you so much!!!~
 感谢有您，前路光明。
