### ISSUE TITLE
error: (-215:Assertion failed) !dsize.empty() in function 'resize'

### ISSUE THREAD

**Issue by Renkosky** [vt-vl-lab/3d-photo-inpainting#46]
I used demo in https://colab.research.google.com/drive/1706ToQrkIZshRSJSHvZ1RuCiM__YX3Bz but last step was failed.

```
 File "main.py", line 65, in <module>
    image = cv2.resize(image, (config['output_w'], config['output_h']), interpolation=cv2.INTER_AREA)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:3688: error: (-215:Assertion failed) !dsize.empty() in function 'resize'
```
What should i do?

**Comment by LemonATsu** [comment]
Please make sure that the input image is located in the correct directory (i.e, `image/`)

**Comment by huwenyue** [comment]
When I test some pictures, I met the same problem too, and I make sure the input image is located in the correct directory(i.e, image/).
