### ISSUE TITLE
"Killed"

### ISSUE THREAD

**Issue by 0lmagalhaes0** [vt-vl-lab/3d-photo-inpainting#48]
Because I'm running the project locally, I changed Torch(device) to 'cpu'. No more problem.
Then, because I use an AMD machine, I set GPU-IDs to -1 in Documentation and Argument.yml. No more problem.

Now I get this:
Start Running 3D_Photo ...
Loading edge model at 1588758535.511688
Loading depth model at 1588758535.9941552
Loading rgb model at 1588758537.5940967
Writing depth ply (and basically doing everything) at 1588758539.200594
Killed

I changed the offscreen_rendering to True, but had no effect, and now I'm out of ideas.

**Comment by LemonATsu** [comment]
It is likely that your machine does not have enough RAM. You can instead use our colab notebook to run the code with free online computing resource.

**Comment by 0lmagalhaes0** [comment]
I'm sorry, I'm still quite a beginner... how do I run the code on the notebook? Must I clone it first somehow?

**Comment by LemonATsu** [comment]
Yes, you have to make a copy of the template first. You can run it can play with it freely after that.
