### ISSUE TITLE
Qt plugin issue

### ISSUE THREAD

**Issue by ouguozhen** [vt-vl-lab/3d-photo-inpainting#49]
"WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)"

And i set the offscreen_render=True in argument.yml, it's still doesn't work

**Comment by LemonATsu** [comment]
What is your OS/platform/environment specs? If it's Linux/Ubuntu, do you have EGL installed?

**Comment by ouguozhen** [comment]
ubuntu16.04, CUDA8.0
i have installed EGL by sudo apt-get install libglfw3-dev libgles2-mesa-dev

**Comment by ouguozhen** [comment]
@LemonATsu 
oh, i solved this issus by [https://github.com/vispy/vispy/issues/1848#issuecomment-613945544](url)

**Comment by LemonATsu** [comment]
@ouguozhen Thanks for the pointer. This would be useful for others that run into the same problem.

**Comment by LiangliangGuo** [comment]
> ubuntu16.04, CUDA8.0
> i have installed EGL by sudo apt-get install libglfw3-dev libgles2-mesa-dev

@ouguozhen Hello, If I work over an SSH/X Window connection, do you know whether the EGL can be used? thanks.

**Comment by ouguozhen** [comment]
it doesn't matter about  the way what your connection

**Comment by ouguozhen** [comment]
@LiangliangGuo it doesn't matter about the way what your connection

**Comment by LiangliangGuo** [comment]
> @LiangliangGuo it doesn't matter about the way what your connection
@ouguozhen I have installed EGL according to what you said by 'sudo apt-get install libglfw3-dev libgles2-mesa-dev', the system has told that the install is successful, but when I use EGL by 'vispy.use(app='egl')', it sill error 'RuntimeError: Could not import backend "EGL": Could not initialize'. I don't konw why? Do you have some suggestions? Thank you very much.

**Comment by ouguozhen** [comment]
@LiangliangGuo try this way [https://github.com/vispy/vispy/issues/1848#issuecomment-613945544](url)

**Comment by LiangliangGuo** [comment]
> @LiangliangGuo try this way [https://github.com/vispy/vispy/issues/1848#issuecomment-613945544](url)

@ouguozhen It seems that the link can't open.

![image](https://user-images.githubusercontent.com/31023581/82015464-65d42080-96b1-11ea-8b8a-5419c96d9d18.png)

**Comment by LiangliangGuo** [comment]
No results matched your search.
You could search all of GitHub or try an advanced search.

> > @LiangliangGuo try this way [https://github.com/vispy/vispy/issues/1848#issuecomment-613945544](url)
> 
> @ouguozhen It seems that the link can't open.
> 
> ![image](https://user-images.githubusercontent.com/31023581/82015464-65d42080-96b1-11ea-8b8a-5419c96d9d18.png)

No results matched your search.
You could search all of GitHub or try an advanced search.

**Comment by ouguozhen** [comment]
@LiangliangGuo sorry，you can copy the link to a newtab, and open it

**Comment by LiangliangGuo** [comment]
> @LiangliangGuo sorry，you can copy the link to a newtab, and open it

@ouguozhen Thank you very much for your help! But I don't know how to get into the path "vispy/vispy/app/backends/_egl.py"
