### ISSUE TITLE
Computer specification

### ISSUE THREAD

**Issue by gw3285** [vt-vl-lab/3d-photo-inpainting#51]
Are there any restrictions on computer specifications and graphics cards required to use this code?

**Comment by LemonATsu** [comment]
I didn't really do the test this but in general, you would want to have at least 8GB of RAMs, and an NVidia card with 4~8GB memory. But this is just a rough spec.

If you find that your system spec is not enough to run our code smoothly, you can use the colab notebook we provided to run it on free online computing resources.

**Comment by wlfcss** [comment]
前期建模的时候似乎只能使用的单线程cpu资源进行计算？这个效率令人头大
