### ISSUE TITLE
Monocuar only?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [vt-vl-lab/3d-photo-inpainting#54]
Fantastic work!
Is there a way to feed MiDaS a stereo pair to increase the accuracy of the depth map generation?  Or perhaps a way to use an existing depth map image and skip the whole MiDaS process?  Thanks in advance!

**Comment by safijari** [comment]
Existing depth map image would be easier to do. You can try doing that by replacing this line to load in your depth map instead (I think it needs to be floating point numbers)
https://github.com/vt-vl-lab/3d-photo-inpainting/blob/2f885467237154db272feeefebead598ec5b68ad/main.py#L66

Also take a look at the read_midas_depth function, it assumes a disparity map is being supplied and converts it into a sort of normalized depth map, so you wanna match that level of processing for your supplied depth map.

https://github.com/vt-vl-lab/3d-photo-inpainting/blob/2f885467237154db272feeefebead598ec5b68ad/utils.py#L942

**Comment by ShihMengLi** [comment]
Thanks @safijari ! Hi, @noobtoob4lyfe , we have modified our code. Now you could edit the depth map and acquire a 3D Photo based on the edited depth map.
Please have a look at `README.md` and `DOCUMENTATION.md` for more details.
