### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by cloudweather** [vt-vl-lab/3d-photo-inpainting#57]
Is there a way to get around for CUDA to get out of memory?
Like decreasing the batch size or something

![unknown](https://user-images.githubusercontent.com/29135514/82760955-a0fcef00-9e29-11ea-8a7c-60fba37d1957.png)

**Comment by LemonATsu** [comment]
You can use our colab notebook if your machine doesn't have enough RAM.

**Comment by iamaviator** [comment]
Have been using it for a while and the results are incredible. I have used it on my extremely edited pic and here are the results. https://imgur.com/gallery/fRJgTfF
