### ISSUE TITLE
Some questions on the paper

### ISSUE THREAD

**Issue by kwea123** [vt-vl-lab/3d-photo-inpainting#58]
I spotted some confusions in the paper. I'm reading [this version](https://arxiv.org/abs/2004.04727) [v2]

1. Figure 13. Isn't the color wrongly placed? Blue (context) should be farther region and red (synthesis) should be closer region.
2. Figure 14. There is no caption. What are the images of the last 3 columns?

Also, the failure case videos don't work on your [website](https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/supp_web/pages/failure.html), please check, thank you!

**Comment by LemonATsu** [comment]
1. The color are swapped in Figure 13. As a side note, we also randomly swap the context/synthesis regions during training as a means of data augmentation.

2. The last three columns are results from StereoMagnification, PB-MPI, and ours (left to right). We are currently revising our arxiv paper and will add captions to clarify this.

3. We will fix this, thanks for pointing it out!
