### ISSUE TITLE
message: Killed ......

### ISSUE THREAD

**Issue by heiheiheibj** [vt-vl-lab/3d-photo-inpainting#59]
(base) root@2901718dd13e:/home/3d-photo-inpainting# python main.py --config argument.yml
running on device cpu
  0%|                                                                                             | 0/1 [00:00<?, ?it/s]Current Source ==>  moon
Running depth extraction at 1591039137.6596677
initialize
device: cpu
start processing
  processing image/moon.jpg (1/1)
torch.Size([1, 3, 384, 384])
finished
Start Running 3D_Photo ...
Loading edge model at 1591039173.303471
Loading depth model at 1591039173.6803665
Loading rgb model at 1591039174.8112936
Writing depth ply (and basically doing everything) at 1591039175.9527135
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    depth_feat_model)
  File "/home/3d-photo-inpainting/mesh.py", line 1843, in write_ply
    input_mesh, info_on_pix, edge_mesh, depth, aft_mark = remove_dangling(input_mesh, edge_ccs, edge_mesh, info_on_pix, image, depth, config)
  File "/home/3d-photo-inpainting/mesh.py", line 764, in remove_dangling
    mesh = refresh_node(single_edge_node, mesh.node[single_edge_node], new_node, dict(), mesh)
AttributeError: 'Graph' object has no attribute 'node'
  0%|                                                                                             | 0/1 [01:23<?, ?it/s]
(base) root@2901718dd13e:/home/3d-photo-inpainting#

win10 + docker 19.03 + ubuntu 18.04
What should I do? thx.

**Comment by LemonATsu** [comment]
Please see #31
