### ISSUE TITLE
Output rendered video directory stays empty

### ISSUE THREAD

**Issue by shlomi-lachmish** [vt-vl-lab/3d-photo-inpainting#6]
Output rendered video directory stays empty:

python main.py --config argument.yml
WARNING: Could not load OpenGL library.
  0%|                                                                                                                            | 0/1 [00:00<?, ?it/s]Current Source ==>  test
initialize
device: cpu
start processing
  processing image/test.jpg (1/1)
torch.Size([1, 3, 288, 384])
finished
Start Running 3D_Photo ...
Killed

**Comment by LemonATsu** [comment]
Seems like your process is killed halfway through the generation process. Perhaps your machine runs out of memory?

Also, it seems like your OpenGL library is not installed correctly.

**Comment by ShihMengLi** [comment]
We load both color inpainting model, depth inpainting model and edge inpainting model when we do the inpainting. This requires a huge memory.
You can use colab ([https://colab.research.google.com/drive/1706ToQrkIZshRSJSHvZ1RuCiM__YX3Bz](url)) instead. It provides you a GPU that meets the requirements.

**Comment by shlomi-lachmish** [comment]
Yes!  it seems that once I extended the docker memory it passed that stage👌
Maybe need to add a hint with the killed message
