### ISSUE TITLE
Can't download the model

### ISSUE THREAD

**Issue by Str4ky** [vt-vl-lab/3d-photo-inpainting#64]
I can't download the model, it say "Invalid Syntax" :(

**Comment by LemonATsu** [comment]
Hi @Straky04,

Did the problem occur when you run the download script?

**Comment by 54696d21** [comment]
you can replace their download script with this one (it disables cert checks)

```
#!/bin/sh
mkdir checkpoints
wget --no-check-certificate https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/color-model.pth
mv color-model.pth checkpoints/.
wget --no-check-certificate https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/depth-model.pth
mv depth-model.pth checkpoints/.
wget --no-check-certificate https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/edge-model.pth
mv edge-model.pth checkpoints/.
wget --no-check-certificate https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/model.pt
mv model.pt MiDaS/.
```

**Comment by david-caylent** [comment]
The filebox.ece.vt.edu site seems to be down ... maybe many people wanted to download the model ... jus like meeee haha

**Comment by damontic** [comment]
The filebox.ece.vt.edu site seems to be down ... maybe many people wanted to download the model ... jus like meeee haha
