### ISSUE TITLE
cynetworkx install fails

### ISSUE THREAD

**Issue by boraturant** [vt-vl-lab/3d-photo-inpainting#65]
Hi,

When installing requirements on windows, cynetworkx install fails. Anyone? Thanks.

 building 'cynetworkx.algorithms.approximation.__init__' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\3DP2\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-6ed12bug\\cynetworkx\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-6ed12bug\\cynetworkx\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-record-bwq1bcjc\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\envs\3DP2\Include\cynetworkx' Check the logs for full command output.

**Comment by xadnem** [comment]
(3DP) C:\Users\windows10\Desktop\3d\3d-photo-inpainting-master\3d-photo-inpainting-master>pip install cynetworkx 2.3
Collecting cynetworkx
  Using cached cynetworkx-2.2rc1.dev20180527181709.tar.gz (14.8 MB)
ERROR: Could not find a version that satisfies the requirement 2.3 (from versions: none)
ERROR: No matching distribution found for 2.3

**Comment by DGriffin91** [comment]
@xadnem I was able to get cynetworkx to building following the instructions here: https://github.com/pattern-inc/cynetworkx/issues/1#issuecomment-660908864

`pip install Cython==3.0a5`
`pip install git+https://github.com/pattern-inc/cynetworkx.git`

**Comment by everyonehello12** [comment]
> @xadnem I was able to get cynetworkx to building following the instructions here: [pattern-inc/cynetworkx#1 (comment)](https://github.com/pattern-inc/cynetworkx/issues/1#issuecomment-660908864)
> 
> `pip install Cython==3.0a5` `pip install git+https://github.com/pattern-inc/cynetworkx.git`

still wont  work

**Comment by Thomas-MMJ** [comment]
cynetworkx worked with

```
pip install Cython==3.0a10
pip install git+https://github.com/pattern-inc/cynetworkx.git

```

I also applied fixes to the warnings  (replace is not, with != and other trivial stuff)

**Comment by shuiyuejihua** [comment]
ubuntu18.04，sudo apt install g++，work for me ，[#98 ](https://github.com/vt-vl-lab/3d-photo-inpainting/issues/98)
