### ISSUE TITLE
Nvidia K-Series K80 Error

### ISSUE THREAD

**Issue by boraturant** [vt-vl-lab/3d-photo-inpainting#66]
Anyone running the model with Nvidia K-Series K80? (on Windows)?

I am getting the following vispy  error, which I believe is related with OpenGL driver support.

 File "C:\ProgramData\Anaconda3\envs\3DP\lib\distutils\version.py", line 335, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'

**Comment by boraturant** [comment]
Closing the issue.

AWS EC2 P GPU Instances does not work, reason being the lack of OpenGL lib.

**Comment by Nerdyvedi** [comment]
@boraturant , Could you share how we could fix this, I am facing the same issue
