### ISSUE TITLE
How can I make it work on CPU only?

### ISSUE THREAD

**Issue by d0null** [vt-vl-lab/3d-photo-inpainting#67]
I tried to change the map_location to torch.device('cpu') but it didn-t work... What are the file I need to change, can anyone help?

**Comment by freeman5** [comment]
Read the documentation, you have to delete the 0 at the gpu argument in argument.yml.

**Comment by d0null** [comment]
Yes, I have and this happend> the process is killed

Start Running 3D_Photo ...
Loading edge model at 1593091614.6673536
Loading depth model at 1593091615.3770957
Loading rgb model at 1593091617.1194363
Writing depth ply (and basically doing everything) at 1593091618.9549518
Killed

**Comment by marius34130** [comment]
I had the same issue. I checked the /var/log/syslog file and it complained about not enought memory(VM with 8Gb). I will try to increase memory to 16Gb

**Comment by marius34130** [comment]
I need 12GB of memory for execute the rending. Now, I have a segmentation fault. i hope it help you

**Comment by d0null** [comment]
> I need 12GB of memory for execute the rending. Now, I have a segmentation fault. i hope it help you

Yep, I got the same error. What should be the next step?


Making video at 1593185095.3476174
fov: 53.13010235415598
Segmentation fault (core dumped)

**Comment by Amenace7899** [comment]
I’m feeling your pain

**Comment by gagan0123** [comment]
About process getting killed(not segmentation fault), most probably its being caused by overheating of the CPU, when you're not utilizing GPU. Suggest you turn your CPU cores to a lower max frequency, then run it again. It will take a bit longer, but it will produce the results.

**Comment by amatiasq** [comment]
@gagan0123 Thanks for the advice. I checked it and temperature was fine.
But found [this issue](https://stackoverflow.com/questions/726690/what-killed-my-process-and-why) and they suggest this command to find the reason for `killed`:

```sh
dmesg -T | grep -E -i -B100 'killed process'
```

And in my case it says

```
Out of memory: Killed process 45722 (python) ...
```

My GPU (GTX 760) is not compatible apparently and I have 7.7Gb memory, guess it's time to upgrade.
