### ISSUE TITLE
Video Generation 

### ISSUE THREAD

**Issue by GregoryBetsey** [vt-vl-lab/3d-photo-inpainting#73]
Is their a way to generate one of the video types instead of all four?

**Comment by LemonATsu** [comment]
You can modify the `traj_types` flag in `argument.yml`. Note that you need to ensure that the length of `traj_type` should be the same as `video_postfix`.

**Comment by GregoryBetsey** [comment]
This is what I did in argument.yml

x_shift_range: [0.00, 0.00, 0.00, 0.00]
y_shift_range: [0.00, 0.00, 0.00, 0.00]
z_shift_range: [-0.05, -0.05, -0.07, -0.07]
traj_types: ['double-straight-line']
video_postfix: ['zoom-in']

and I got this error 

Traceback (most recent call last):
  File "main.py", line 34, in <module>
    sample_list = get_MiDaS_samples(config['src_folder'], config['depth_folder'], config, config['specific'])
  File "C:\Users\gregb\Documents\Python\3D-Photo-Inpainting\utils.py", line 845, in get_MiDaS_samples
    'video_postfix' should be equal."
AssertionError: The number of elements in 'traj_types', 'x_shift_range', 'y_shift_range', 'z_shift_range' and  'video_postfix' should be equal.
