### ISSUE TITLE
dolly-zoom-in arguments

### ISSUE THREAD

**Issue by sulram** [vt-vl-lab/3d-photo-inpainting#76]
Hello there!

I'm curious because `dolly-zoom-in` have the same arguments of `zoom-in`.
Why the video output is different?

Is there another argument involved?

**Comment by LemonATsu** [comment]
In `dolly-zoom-in`, we will recalculate the fov to make the point/object of interest stay at the same size (see: https://github.com/vt-vl-lab/3d-photo-inpainting/blob/e6872a8f7452c71b0f348d3dfcd7c13e1b8b69c1/mesh.py#L2242).

**Comment by sulram** [comment]
Great, thank you for the great work! @LemonATsu
