### ISSUE TITLE
How to use GPU in Colab?

### ISSUE THREAD

**Issue by suissemaxx** [vt-vl-lab/3d-photo-inpainting#8]
Thanks very much for making this available! Very impressive!

I use the Colab notebook that you provided with a GPU instance. The code runs perfectly fine but I noticed that according to the log print out the GPU isn't used **but rather the CPU**. 

How can I switch to GPU? Or is the print out wrong?

Thanks in advance for any insight on that.

```
initialize
device: cpu # <--- shouldn't this print out to "gpu" or is actually the cpu being used?
start processing
…
```

**Comment by LemonATsu** [comment]
The line `device: cpu` is the log for the depth estimation model (MiDas), which works fast enough on CPU (usually only take 2-3 second). 

The actual inpainting models for the 3D photo network will operate on the device specified in `argument.yml` (GPU by default).

**Comment by suissemaxx** [comment]
Thanks!
