### ISSUE TITLE
bash download.sh  windows 10

### ISSUE THREAD

**Issue by xadnem** [vt-vl-lab/3d-photo-inpainting#80]
(3DP) C:\Users\windows10\Desktop\3d\3d-photo-inpainting-master\3d-photo-inpainting-master>chmod +x download.sh

(3DP) C:\Users\windows10\Desktop\3d\3d-photo-inpainting-master\3d-photo-inpainting-master>bash download.sh
mkdir: cannot create directory 'checkpoints': File exists
download.sh: line 3: wget: command not found
mv: cannot stat 'color-model.pth': No such file or directory
download.sh: line 5: wget: command not found
mv: cannot stat 'depth-model.pth': No such file or directory
download.sh: line 7: wget: command not found
mv: cannot stat 'edge-model.pth': No such file or directory
download.sh: line 9: wget: command not found
mv: cannot stat 'model.pt': No such file or directory

(3DP) C:\Users\windows10\Desktop\3d\3d-photo-inpainting-master\3d-photo-inpainting-master>./download.sh
'.' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

(3DP) C:\Users\windows10\Desktop\3d\3d-photo-inpainting-master\3d-photo-inpainting-master>

**Comment by 54696d21** [comment]
you can replace their download script with this one (it disables cert checks)

```
#!/bin/sh
mkdir checkpoints
wget --no-check-certificate https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/color-model.pth
mv color-model.pth checkpoints/.
wget --no-check-certificate https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/depth-model.pth
mv depth-model.pth checkpoints/.
wget --no-check-certificate https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/edge-model.pth
mv edge-model.pth checkpoints/.
wget --no-check-certificate https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/model.pt
mv model.pt MiDaS/.
```

**Comment by LemonATsu** [comment]
@xadnem it appears that you do not have wget on your machine/env.
