### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by bibhas2** [vt-vl-lab/3d-photo-inpainting#82]
wget is failing inside ``download.sh`` because certificate of ``https://filebox.ece.vt.edu`` has expired.

I worked around the issue by replacing ``wget`` with ``curl -k``.

**Comment by DGriffin91** [comment]
It appears that `https://filebox.ece.vt.edu` is down now (As far as I can tell, both wget & curl -k not working) are these files mirrored elsewhere?

**Comment by JanWerder** [comment]
It's still down. Maybe move the models to Github?

**Comment by James-Slam** [comment]
https://mega.nz/folder/XMlWiASJ#ABLGW4-BaFdLFeH0GcZy0A

**Comment by 0SmooK0** [comment]
It's fine now and I believe can be closed.
