### ISSUE TITLE
Missing models at https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/

### ISSUE THREAD

**Issue by turkeyphant** [vt-vl-lab/3d-photo-inpainting#84]
--2020-07-22 21:37:02--  https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/color-model.pth
Resolving filebox.ece.vt.edu (filebox.ece.vt.edu)... 128.173.88.43
Connecting to filebox.ece.vt.edu (filebox.ece.vt.edu)|128.173.88.43|:443... failed: Connection refused.
mv: cannot stat 'color-model.pth': No such file or directory
--2020-07-22 21:37:02--  https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/depth-model.pth
Resolving filebox.ece.vt.edu (filebox.ece.vt.edu)... 128.173.88.43
Connecting to filebox.ece.vt.edu (filebox.ece.vt.edu)|128.173.88.43|:443... failed: Connection refused.
mv: cannot stat 'depth-model.pth': No such file or directory
--2020-07-22 21:37:02--  https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/edge-model.pth
Resolving filebox.ece.vt.edu (filebox.ece.vt.edu)... 128.173.88.43
Connecting to filebox.ece.vt.edu (filebox.ece.vt.edu)|128.173.88.43|:443... failed: Connection refused.
mv: cannot stat 'edge-model.pth': No such file or directory
--2020-07-22 21:37:02--  https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/model.pt
Resolving filebox.ece.vt.edu (filebox.ece.vt.edu)... 128.173.88.43
Connecting to filebox.ece.vt.edu (filebox.ece.vt.edu)|128.173.88.43|:443... failed: Connection refused.
mv: cannot stat 'model.pt': No such file or directory

**Comment by gagan0123** [comment]
The server seems down, if anyone else has those models, please share.

**Comment by James-Slam** [comment]
https://mega.nz/folder/XMlWiASJ#ABLGW4-BaFdLFeH0GcZy0A

**Comment by LemonATsu** [comment]
@turkeyphant @gagan0123 
We have updated the download script so that it will download from backup URLs. Let us know if the problem still exists.

**Comment by turkeyphant** [comment]
> @turkeyphant @gagan0123
> We have updated the download script so that it will download from backup URLs. Let us know if the problem still exists.

Now getting the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/imageio/plugins/pillow.py", line 669, in pil_try_read
    im.getdata()[0]
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 1249, in getdata
    self.load()
  File "/usr/local/lib/python3.6/dist-packages/PIL/ImageFile.py", line 247, in load
    "(%d bytes not processed)" % len(b)
OSError: image file is truncated (6 bytes not processed)

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    sample_list = get_MiDaS_samples(config['src_folder'], config['depth_folder'], config, config['specific'])
  File "/content/3d-photo-inpainting/utils.py", line 874, in get_MiDaS_samples
    H, W = imageio.imread(sdict['ref_img_fi']).shape[:2]
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/functions.py", line 186, in get_reader
    return format.get_reader(request)
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/format.py", line 170, in get_reader
    return self.Reader(self, request)
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/format.py", line 221, in __init__
    self._open(**self.request.kwargs.copy())
  File "/usr/local/lib/python3.6/dist-packages/imageio/plugins/pillow.py", line 429, in _open
    return PillowFormat.Reader._open(self, pilmode=pilmode, as_gray=as_gray)
  File "/usr/local/lib/python3.6/dist-packages/imageio/plugins/pillow.py", line 135, in _open
    pil_try_read(self._im)
  File "/usr/local/lib/python3.6/dist-packages/imageio/plugins/pillow.py", line 680, in pil_try_read
    raise ValueError(error_message)
ValueError: Could not load "" 
Reason: "image file is truncated (6 bytes not processed)"
Please see documentation at: http://pillow.readthedocs.io/en/latest/installation.html#external-libraries
```

**Comment by LemonATsu** [comment]
Looks like your image is not placed in `image/`

**Comment by gagan0123** [comment]
> @turkeyphant @gagan0123
> We have updated the download script so that it will download from backup URLs. Let us know if the problem still exists.

Thanks :+1:

**Comment by turkeyphant** [comment]
> Looks like your image is not placed in `image/`

It was. I think it might not support whitespace in filenames.

**Comment by gagan0123** [comment]
@turkeyphant It would be better to create another issue, rather than asking about a different issue on this issue. Both of these are unrelated, as far as I know.
