### ISSUE TITLE
Error when using custom depth map

### ISSUE THREAD

**Issue by James-Slam** [vt-vl-lab/3d-photo-inpainting#88]
Using Google's Colab

Non-default Argument settings:
depth_format: '.png'
require_midas: False
save_ply: False

I made the png in GIMP
![shinobu](https://user-images.githubusercontent.com/3708601/88352907-8a8bea80-cd29-11ea-85df-cd92324b24b7.png)

running on device 0
  0% 0/1 [00:00<?, ?it/s]Current Source ==>  shinobu
Running depth extraction at 1595553061.1740317
  0% 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    vis_photos, vis_depths = sparse_bilateral_filtering(depth.copy(), image.copy(), config, num_iter=config['sparse_iter'], spdb=False)
  File "/content/3d-photo-inpainting/bilateral_filtering.py", line 31, in sparse_bilateral_filtering
    vis_image[u_over > 0] = np.array([0, 0, 0])
IndexError: boolean index did not match indexed array along dimension 2; dimension is 3 but corresponding boolean dimension is 6

**Comment by LemonATsu** [comment]
Try saving your depth map in grayscale and see if it works.

**Comment by James-Slam** [comment]
> Try saving your depth map in grayscale and see if it works.

That did the trick, thank you!
