### ISSUE TITLE
Warnings while running on an SSH session - no output videos

### ISSUE THREAD

**Issue by MahadevanSrinivasan** [vt-vl-lab/3d-photo-inpainting#9]
I get the following warnings while running headless:
```
Current Source ==>  md
initialize
device: cpu
start processing
  processing image/md.jpg (1/1)
torch.Size([1, 3, 384, 288])
finished
Start Running 3D_Photo ...
Writing mesh file mesh/md.ply ...
53.13010235415598
WARNING: QXcbConnection: Could not connect to display
WARNING: Could not connect to any X display.
```

I do see the md.ply file in the mesh folder and md.npy file in the depth folder. Just no videos though. Can this not be run without GUI?

**Comment by LemonATsu** [comment]
Try setting `offscreen_rendering` in argument.yml to `True` to enable rendering without GUI environment.

**Comment by MahadevanSrinivasan** [comment]
Thanks for your reply. I did that and get the following error now:

```
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    vispy.use(app='egl')
  File "/home/md/anaconda2/envs/3DP/lib/python3.7/site-packages/vispy/util/wrappers.py", line 97, in use
    use_app(app)
  File "/home/md/anaconda2/envs/3DP/lib/python3.7/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/home/md/anaconda2/envs/3DP/lib/python3.7/site-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/home/md/anaconda2/envs/3DP/lib/python3.7/site-packages/vispy/app/application.py", line 235, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "EGL":
Could not initialize
```

**Comment by LemonATsu** [comment]
Try installing EGL by running: `sudo apt-get install libgles2-mesa-dev`. Let us know if it works. Thanks

**Comment by puppet101** [comment]
@LemonATsu 
I get the same error, but I am using CentOS 7,  what packages should I install to run it with offscreen rendering?

**Comment by ShihMengLi** [comment]
Maybe this one?
[https://centos.pkgs.org/7/centos-x86_64/mesa-libGLU-devel-9.0.0-4.el7.x86_64.rpm.html](url)

**Comment by MahadevanSrinivasan** [comment]
> Try installing EGL by running: `sudo apt-get install libgles2-mesa-dev`. Let us know if it works. Thanks

I have that package installed already. But still see the same error

**Comment by dantuluri** [comment]
I've been tackling this issue as well.
I don't see the reason for having all those render() functions in mesh.py. At this point it seems like xvfb-run is the best temporary option.

The weird thing about this is:
It runs perfectly on Colab but on a Docker container or even another Jupyter notebook these vispy issues come up

**Comment by dantuluri** [comment]
The issue here is: regardless of offscreen_render, you will still need vispy's scene module to create canvases for mesh.py to run.

I've installed all the packages  but strangely I can't replicate this anywhere other than colab (when I run this on a jupyter notebook I run into "no screen" errors

**Comment by MoePus** [comment]
> Try setting `offscreen_rendering` in argument.yml to `True` to enable rendering without GUI environment.

This works for win10 wsl unbuntu 18.04

**Comment by dilenpant** [comment]
@LemonATsu I'm checked with Mac and linux different devices but stuck here.

Traceback (most recent call last):
  File "main.py", line 68, in <module>
    map_location=torch.device(device))
  File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 740, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 132, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 116, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by MahadevanSrinivasan** [comment]
> @LemonATsu I checked with Mac and linux different devices but stuck here.
> 
> Traceback (most recent call last):
> File "main.py", line 68, in
> map_location=torch.device(device))
> File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
> return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
> File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
> result = unpickler.load()
> File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load
> deserialized_objects[root_key] = restore_location(obj, location)
> File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 740, in restore_location
> return default_restore_location(storage, str(map_location))
> File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location
> result = fn(storage, location)
> File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 132, in _cuda_deserialize
> device = validate_cuda_device(location)
> File "/home/dilendra/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 116, in validate_cuda_device
> raise RuntimeError('Attempting to deserialize object on a CUDA '
> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

Set the gpus field in the arugment.yml file to -1 to fallback to CPU

**Comment by MahadevanSrinivasan** [comment]
> > Try setting `offscreen_rendering` in argument.yml to `True` to enable rendering without GUI environment.
> 
> This works for win10 wsl unbuntu 18.04

Did you have to install any new packages? I tried on Win10 WSL Ubuntu 16.04 and it does not work.

**Comment by MoePus** [comment]
> > > Try setting `offscreen_rendering` in argument.yml to `True` to enable rendering without GUI environment.
> > 
> > 
> > This works for win10 wsl unbuntu 18.04
> 
> Did you have to install any new packages? I tried on Win10 WSL Ubuntu 16.04 and it does not work.
Only libgles2-mesa-dev.
My wsl ubuntu is new installed on win10 1909.
And i have aslo run `export DISPLAY=:0`

**Comment by davideandres95** [comment]
> > Try setting `offscreen_rendering` in argument.yml to `True` to enable rendering without GUI environment.
> 
> This works for win10 wsl unbuntu 18.04

Well it does not work in ubuntu 16.04. Any other suggestions?

**Comment by cahitatlas** [comment]
I get same problem on macOS Catalina
Normaly when i try with default yml file, i get that result: 

(3DP) bash-3.2$ python main.py --config argument.yml
  0%|                                                                                                 | 0/1 [00:00<?, ?it/s]Current Source ==>  einstein
initialize
device: cpu
  0%|                                                                                                 | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    config['MiDaS_model_ckpt'], MonoDepthNet, MiDaS_utils, target_w=640)
  File "/Users/cahitatlas/Downloads/3d-photo-inpainting-master/MiDaS/run.py", line 27, in run_depth
    model = Net(model_path)
  File "/Users/cahitatlas/Downloads/3d-photo-inpainting-master/MiDaS/monodepth_net.py", line 52, in __init__
    self.load(path)
  File "/Users/cahitatlas/Downloads/3d-photo-inpainting-master/MiDaS/monodepth_net.py", line 88, in load
    parameters = torch.load(path)
  File "/Users/cahitatlas/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/cahitatlas/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/cahitatlas/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
**FileNotFoundError: [Errno 2] No such file or directory: 'MiDaS/model.pt'**

**I deleted MiDaS_model_ckpt: 
than i get result :**

Start Running 3D_Photo ...
  0%|                                                                                                 | 0/1 [00:13<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    map_location=torch.device(device))
  File "/Users/cahitatlas/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/cahitatlas/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/cahitatlas/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/edge-model.pth'

**Comment by LemonATsu** [comment]
@cahitatlas Try run the `download.sh` script to download all the pre-trained weights.

**Comment by lizhengwei1992** [comment]
> Try installing EGL by running: `sudo apt-get install libgles2-mesa-dev`. Let us know if it works. Thanks

I also have the same error "RuntimeError: Could not import backend "EGL":
" after install  libgles2-mesa-dev.

**Comment by lizhengwei1992** [comment]
> > Try installing EGL by running: `sudo apt-get install libgles2-mesa-dev`. Let us know if it works. Thanks
> 
> I have that package installed already. But still see the same error

Use os.environ['DISPLAY']= ':0' in main.py after running: `sudo apt-get install libgles2-mesa-dev`, fixed it !

**Comment by LemonATsu** [comment]
@lizhengwei1992 Thanks for letting us know. This would be useful for others that have the same problem.

**Comment by mohit1997** [comment]
I changed two things,

On the client side while logging in, use 
```bash
ssh -v -X user@server
```

then in the `argument.yml` file update
```YAML
offscreen_rendering: True
```

**Comment by yfq512** [comment]
I solved same error follow this:
https://github.com/vispy/vispy/issues/1848#issuecomment-613945544
