### ISSUE TITLE
Viewing Mesh files

### ISSUE THREAD

**Issue by wtesler** [vt-vl-lab/3d-photo-inpainting#90]
When I attempt to view the PLY mesh files, they always come out wrong, like this:

![Annotation 2020-07-26 135532](https://user-images.githubusercontent.com/2490505/88487088-d2885880-cf47-11ea-97f6-dafd1dc67602.png)

How can I properly view the mesh file. Is it really in PLY format?

**Comment by wtesler** [comment]
I realize now that it was in a proper format. I just needed to rotate the mesh properly. Also, the mesh has these long lines in the area of occlusion but that is to be expected.

**Comment by laihaotao** [comment]
> I realize now that it was in a proper format. I just needed to rotate the mesh properly. Also, the mesh has these long lines in the area of occlusion but that is to be expected.

Hi, I also try to visualize the generated mesh, what kind of tool you use to do the visualization and how to what degree you rotate it ?

**Comment by wtesler** [comment]
You can open it in Blender and then rotate it arbitrarily until you find the spot that looks good
