### ISSUE TITLE
Training Codes

### ISSUE THREAD

**Issue by HieuPhan33** [vt-vl-lab/3d-photo-inpainting#92]
Hi,
Thanks for publishing the codes and the pre-trained models.

I would like to train your models on my dataset. Could you please share the training codes?

Thank you in advance.

**Comment by violetamenendez** [comment]
Hi,

I'm also interested in the training code. Did you manage to train it? I'm finding it hard to do it myself.

Thanks

**Comment by HieuPhan33** [comment]
I couldn't train it at the end.
