### ISSUE TITLE
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:3688: error: (-215:Assertion failed) !dsize.empty() in function 'resize'

### ISSUE THREAD

**Issue by huwenyue** [vt-vl-lab/3d-photo-inpainting#94]
https://colab.research.google.com/drive/1706ToQrkIZshRSJSHvZ1RuCiM__YX3Bz?usp=sharing
![image](https://user-images.githubusercontent.com/20535538/88782579-55b3e380-d1c0-11ea-9dd9-59fc67497c89.png)

**Comment by LemonATsu** [comment]
Make sure that the image is placed in the correct path, and `argument.yml` is set accordingly.
