### ISSUE TITLE
Requirements for GPU?

### ISSUE THREAD

**Issue by GitHuhl** [vt-vl-lab/3d-photo-inpainting#96]
Fantastic work I got this running in an Ubuntu VM. I’d like to try a dedicated bare metal installation for GPU processing. Is tensowflow required or do I just need to have the nvidia drivers installed? My card isn’t very new (compute capability 3.0 I believe) and I’m not gonna go through the pain of compiling tensorflow. Please let me know what the requirements are for GPU before I delve into installing Ubuntu and this all up again. Again great work

**Comment by geborskimateusz** [comment]
Hi. I would like to get more info also. I am running Ubnutu and I cannot setup project with GPU. ALways getting 
`Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`

Any hints here?
